### ISSUE TITLE
Dyeable mankini incompatible with servers (?)

### ISSUE THREAD

**Issue by rfwainug** [MasterAbdoTGM50/Mankini#23]
net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net.minecraft.client.renderer.color.IItemColorat net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89) ~[forge-1.12.2-14.23.5.2793-universal.jar:?]at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:599) ~[forge-1.12.2-14.23.5.2793-universal.jar:?]at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source) ~[?:?]at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[forge-1.12.2-14.23.5.2793-universal.jar:?]at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[forge-1.12.2-14.23.5.2793-universal.jar:?]at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593) ~[Loader.class:?]at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]Caused by: java.lang.NoClassDefFoundError: net.minecraft.client.renderer.color.IItemColorat java.lang.J9VMInternals.prepareClassImpl(Native Method) ~[?:1.8.0_192]at java.lang.J9VMInternals.prepare(J9VMInternals.java:302) ~[?:1.8.0_192]at java.lang.Class.getMethods(Class.java:1367) ~[?:1.8.0_192]at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82) ~[EventBus.class:?]at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82) ~[AutomaticEventSubscriber.class:?]... 31 moreCaused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.color.IItemColorat net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:934) ~[?:1.8.0_192]at java.lang.ClassLoader.loadClass(ClassLoader.java:879) ~[?:1.8.0_192]at java.lang.ClassLoader.loadClass(ClassLoader.java:862) ~[?:1.8.0_192]at java.lang.J9VMInternals.prepareClassImpl(Native Method) ~[?:1.8.0_192]at java.lang.J9VMInternals.prepare(J9VMInternals.java:302) ~[?:1.8.0_192]at java.lang.Class.getMethods(Class.java:1367) ~[?:1.8.0_192]at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82) ~[EventBus.class:?]at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82) ~[AutomaticEventSubscriber.class:?]... 31 moreCaused by: java.lang.NullPointerExceptionat net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:934) ~[?:1.8.0_192]at java.lang.ClassLoader.loadClass(ClassLoader.java:879) ~[?:1.8.0_192]at java.lang.ClassLoader.loadClass(ClassLoader.java:862) ~[?:1.8.0_192]at java.lang.J9VMInternals.prepareClassImpl(Native Method) ~[?:1.8.0_192]at java.lang.J9VMInternals.prepare(J9VMInternals.java:302) ~[?:1.8.0_192]at java.lang.Class.getMethods(Class.java:1367) ~[?:1.8.0_192]at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82) ~[EventBus.class:?]at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82) ~[AutomaticEventSubscriber.class:?]... 31 more

**Comment by Mrbysco** [comment]
Uploaded v1.3.3.1, Could you try this version?
