### ISSUE TITLE
[Bug|Major] Server crash using Mankini Mod v1.2.0

### ISSUE THREAD

**Issue by SnowShock35** [MasterAbdoTGM50/Mankini#6]
Crash on server start.

http://paste.ee/p/WtGoX

Forge 10.13.4.1448
Minecraft 1.7.10
Mankini 1.2.0
FastCraft Enabled

Contact if need more information

**Comment by kenny2810** [comment]
Hey, had some free time and decided to take another look at the Mankini mod. Did you ever get a chance to test the updated version I sent you via twitter DM?

**Comment by MasterAbdoTGM50** [comment]
I didn't recieve anything sadly

**Comment by kenny2810** [comment]
Sent it to you on twitter Abdo

**Comment by kenny2810** [comment]
Fixed in latest update
